### ISSUE TITLE
Change request: column type selection when creating new building block

### ISSUE THREAD

**Issue by akirbis** [nfdi4plants/arcmanager_frontend#7]
## Current situation

When adding a new building block to an annotation table, the column type can be selected from a drop-down menu. The current options are:

Parameter, Factor, Characteristic, Component, Date, Performer, Protocol

<img width="413" alt="2024-07-25_ARCmanager_building_block_selection" src="https://github.com/user-attachments/assets/4d616620-4c15-4ea2-9451-0b1062c082df">

## Change request

According to [ISA-XLSX specification](https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#annotation-table-sheets), allowed column types for annotation tables are:

Characterisitc, Factor, Parameter, Component, Comment +
5 different protocol column types: Protocol REF, Protocol Version, Protocol Description, Protocol Uri, Protocol Type

All other column types are out of scope of the specification, so it would probably be a good idea to remove `Date`, `Performer`, `Protocol` from the current selection and add `Comment`, as well as the 5 protocol column types, instead.

**Comment by Lu98Be** [comment]
I removed `Date`  and `Performer` and added `Comment` and the different protocol columns as you mentioned.

![parameter list](https://github.com/user-attachments/assets/1c0841b1-eac9-4508-b73c-2802d2b85e47)


Also have I changed the way you add protocol columns now. Instead of adding the 5 type of protocols to the list I added a checkbox for each protocol. It more asthetic and user friendly that way, as you now can add mutliple column types at once.

![protocol parameter](https://github.com/user-attachments/assets/ab3beb01-bdba-4d7a-9fa4-6756645a4e89)

I will push the change later to the live version and the repo, as soon as I added the other stuff.

**Comment by akirbis** [comment]
Looks good so far, thanks for the quick adjustment!

Two small additions:

(1) It looks like the new protocol column names don't have whitespace characters in the annotation table. I think the whitespace is part of the [specification](https://github.com/nfdi4plants/ARC-specification/blob/main/ISA-XLSX.md#protocol-columns), so it should also occur in the column name fields (e.g. "Protocol Type" instead of "ProtocolType".

(2) All protocol columns are limited to occur at most one time in each annotation table. Can we somehow prevent users from adding more than one column of each type?

**Comment by Lu98Be** [comment]
I think the `ProtocolType` and `ProtocolREF` you see on the screenshot came from a template.
Because when you add the protocol columns it should look like this:

![protocol parameter](https://github.com/user-attachments/assets/a3e7def4-45b4-4794-aa5d-f278479a331e)

(you can also see the arrows to move the columns already ^^)

I also added a check whether the exact protocol columns, you want to add, aren't already there.
Therefore it shouldn't be possivle to add more than one of each type of protocol column.

**Comment by Lu98Be** [comment]
changed in new version 0.9.2
